### ISSUE TITLE
OSC to OBS

### ISSUE THREAD

**Issue by vigliensoni** [insertions/eastern-bloc-workshop#2]

**Comment by jeraman** [comment]
It seems there are two possible approaches to solve this issue:
1. **OSC to Keystrokes:** As discussed before. Can potentially work by using [midiStrokes](charlie-roberts.com/midiStroke/) or Gene Kogan's [Keyboard OSC](https://github.com/ml4a/ml4a-ofx/tree/master/osc-modules/KeyboardOSC).
2. **OBS Remote:** This would allow us to use [OBS Software via websockets](https://github.com/Palakis/obs-websocket).

Decided to give the first option a try. I'll keep the thread updated as research advances.

**Comment by jeraman** [comment]
[Gene Kogan's Keyboard OSC](https://github.com/ml4a/ml4a-ofx/tree/master/osc-modules/KeyboardOSC) works great for this goal. 

I've manually forked his code to a new repository [here](https://github.com/insertions/KeyboardOSC).

Issue solved.
